on:
  release:
    types: [released]

name: Release a new Version of the Extension

jobs:
  release:
    name: Release a new Version of the Extension
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - name: Publish to Visual Studio Marketplace
      run: npm run publish
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
    - name: Determine Artifact Name
        run: echo "ARTIFACT_NAME=djinni-syntax-highlighting-$(npm run semver --silent).vsix" >> $GITHUB_ENV
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ $(curl -sL https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.upload_url') }}
        asset_path: ./${{ env.ARTIFACT_NAME }}
        asset_name: ${{ env.ARTIFACT_NAME }}
        asset_content_type: application/zip
